sources:
  - from: https://deno.land/x/denoflow@0.0.28/sources/rss.ts
    args:
      - https://actionsflow.github.io/test-page/hn-rss.xml
    limit: 1
    force: true
steps:
  - run: console.log('item',ctx.item)
  - use: fetch
    # Open: <https://requestbin.com/r/enyvb91j5zjv9/23eNPamD4DK4YK1rfEB1FAQOKIj> , See live webhook request. replace your webhook here
    env:
      DISCORD_WEBHOOK: https://enyvb91j5zjv9.x.pipedream.net/
    args:
      - ${{ctx.env.DISCORD_WEBHOOK}}
      - method: POST
        headers:
          Content-Type: application/json
        body: ${{ JSON.stringify({content:ctx.item.title.value}) }}
